TWEAK_NAME = Crystal
$(TWEAK_NAME)_FILES = Crystal.x
$(TWEAK_NAME)_FRAMEWORKS = Foundation
$(TWEAK_NAME)_EXTRA_FRAMEWORKS = Cephei
$(TWEAK_NAME)_CFLAGS = -fobjc-arc
ADDITIONAL_CFLAGS += -DTHEOS_LEAN_AND_MEAN

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
